### ISSUE TITLE
Can't roll initiative from sheet

### ISSUE THREAD

**Issue by west1778** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#17]
Cannot roll initiative from clicking on the sheet. Works in the combat tracker though.

**Comment by akrigline** [comment]
@west1778 can you confirm if this works in the default dnd5e Sheet? Last I checked this wasn't possible there. I'm not opposed to adding it to my sheet, but I'd like to know if it's something I need to add or fix.

**Comment by west1778** [comment]
I will check when I go to lunch today. Sorry I'm the GM so I don't usually use those sheets to know off hand.

**Comment by west1778** [comment]
You're correct it's not rollable on the stock 5e sheet I think I spoiled them using another test sheet that allowed them to do it and when they couldn't they thought it was a bug sorry to have bothered you.

**Comment by akrigline** [comment]
I'll keep this on the todo list as an enhancement! Thanks for the feedback!

**Comment by west1778** [comment]
Thanks that would be awesome!

**Comment by akrigline** [comment]
Turns out in dnd5e 0.99 this is default behavior, in release 0.9.0 I enabled it on this sheet as well.
