### ISSUE TITLE
Death saving throws not functioning 

### ISSUE THREAD

**Issue by JshReaper** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#25]
When using this sheet the Death saving throw button does nothing, it doesn't throw an error either.

To make sure I did not have a conflicting module I Created a test world with only this module enabled.

I have run into the same issue with other custom sheets.

**Comment by akrigline** [comment]
Thanks for the report! I'll take a look at this asap.

**Comment by akrigline** [comment]
Fixed in 0.9.4
