### ISSUE TITLE
Actor sheet will not open.

### ISSUE THREAD

**Issue by AlanDNelson** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#29]
I am pretty sure this error is from the Compact DnDBeyond 5e Character Sheet module.  Actor sheet for any actor where this sheet would open just fails.  Error message from Electron browser is as follows:

![image](https://user-images.githubusercontent.com/36895037/100189898-37829980-2ebb-11eb-871a-dc28c880087d.png)

Using version:  0.10.1

**Comment by akrigline** [comment]
uh oh. thanks for the report! I'll take a look asap.

**Comment by akrigline** [comment]
fixed in 0.10.2 (this is what I get for copying code from tidy sheet 😅, I forgot to check if the helpers here were foundry core and they were not)
