### ISSUE TITLE
Display passive skill scores.

### ISSUE THREAD

**Issue by ChartrueseAubergine** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#30]
It would be really helpful to display passive skill scores as well, similar to below:

<img width="225" alt="Screen Shot 2020-11-25 at 14 45 05" src="https://user-images.githubusercontent.com/39021788/100289096-fc20b300-2f2c-11eb-8aa9-66b869a087fe.png">

NOTE: IIUC, Skills with advantage gain +5 to passive, and there is a feat to gain additional +5 passive perception/investigation.

https://www.dndbeyond.com/sources/basic-rules/using-ability-scores#PassiveChecks
https://roll20.net/compendium/dnd5e/Ability%20Checks#h-Passive%20Checks
https://5thsrd.org/rules/abilities/ability_checks/#passive-checks
> Here’s how to determine a character’s total for a passive check:
> 10 + all modifiers that normally apply to the check
> 
> If the character has advantage on the check, add 5. For disadvantage, subtract 5. The game refers to a passive check total as a score.
(Only one source of advantage can add that +5.)

https://www.dndbeyond.com/feats/observant
http://dnd5ed.wikidot.com/feat:observant
> You have a +5 bonus to your passive Wisdom (Perception) and passive Intelligence (Investigation) scores.
(Separate from advantage.)

There is also Inquisitive Rogue's Steady Eye feature. But this seems harder to account for. Maybe could do just "(passive/half-speed-passive)" instead of just "(passive)" that the example shows? Optional, since it otherwise seems a pain?
https://www.dndbeyond.com/sources/xgte/subclasses#Inquisitive
> At 9th level, you gain advantage on any Wisdom (Perception) or Intelligence (Investigation) check if you move no more than half your speed on the same turn.
(Could drop this if player otherwise already has advantage from prior.)

**Comment by akrigline** [comment]
Thanks for the feedback! I think I ditched these because I personally haven't found them super useful in my games and I wanted to save some space. I don't hate the idea of having this in a `title` or tooltip of some sort though, do you think that would be sufficient?

As for calculations, since this is already present in the stock character sheet, I shouldn't need to calculate things. I don't know if the stock calculations handle these passive boosts or what have you, but that'll be distinctly out of scope for this character sheet display overhaul.

**Comment by ChartrueseAubergine** [comment]
My DM wanted it for some reason. I guess he keeps character sheets all open on another monitor? Maybe make it a checkbox in settings to display them inline? He probably /really/ only uses passive stealth, perception, and investigation. Maybe could add those to a single row in between inspiration and the skills section??

Oh that's good that the system pre-calculates that stuff. :-) I haven't delved very deeply into modding yet.

**Comment by ChartrueseAubergine** [comment]
Maybe also passive insight? 🤔

**Comment by akrigline** [comment]
Coming in 0.10.3:
- New World Settings to display the following permanently on sheets:
  - Passive Perception
  - Passive Insight
  - Passive Investigation
  - Passive Stealth
- Hover over any skill row to show the passive in a `title`

**Comment by ChartrueseAubergine** [comment]
Looks good! Thank you!!
