### ISSUE TITLE
Passive Persuasion instead of Passive Perception displayed in sheet.

### ISSUE THREAD

**Issue by ChartrueseAubergine** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#32]
<img width="319" alt="Screen Shot 2020-11-29 at 23 45 23" src="https://user-images.githubusercontent.com/39021788/100581717-ff090400-329c-11eb-967e-538c532be3f2.png">

<img width="237" alt="Screen Shot 2020-11-29 at 23 43 37" src="https://user-images.githubusercontent.com/39021788/100581623-da149100-329c-11eb-869b-bd53be4751ea.png">

Seems like an autocomplete mistake? ;-)

**Comment by ChartrueseAubergine** [comment]
(Both string and value are showing "Persuasion")

**Comment by akrigline** [comment]
Not my brightest moment. 🤦 
Thanks for the report!

**Comment by akrigline** [comment]
Fixed in 0.10.4
