### ISSUE TITLE
Option to Hide Resources

### ISSUE THREAD

**Issue by DrWiFi** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#34]
It is confusing to some of my players having Resources able to be tracked in both the top (Resources 1-3) and in the features themselves.
This duplicates due to how the importers from dndbeyond seem to pull stuff in.
While it is not specific to this sheet, my players all prefer the layout you designed.
Could there be an option to hide the Resources 1-3 which will free up a bit of space, and prevent duplicate tracking of these resources for those who want to track via the feature listing itself?
Thank you

**Comment by akrigline** [comment]
@DrWiFi thanks for the feedback!

I'm hesitant to mess with this as it's got some high chances of confusion. Can you do me a favor and try using [5e Sheet Resources Plus](https://github.com/ardittristan/5eSheet-resourcesPlus) to set the sheet's resources to "0"? 

I don't know if that will work but if so, that's a potential I can point to for people who think similarly.

**Comment by DrWiFi** [comment]
Thank you for the quick response. That module worked great for removing them!

**Comment by akrigline** [comment]
Nice! I'll mark this as won't fix then. Thanks for letting me know it worked!
