### ISSUE TITLE
Add a "Journal" tab to the character sheets

### ISSUE THREAD

**Issue by Brahman38** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#39]
It would be really cool to see a Journal tab on the character sheets similar to Tidy5e Sheet.  Included a screenshot of what those look like. This would allow players a nice neat place to organize their own notes without having to use another application and/or clog up the journal entries tab =)

![Screenshot (17)](https://user-images.githubusercontent.com/76495990/102928880-8a725100-4467-11eb-984c-48509bf9894d.png)

**Comment by akrigline** [comment]
I've gone and blown this out of proportion:
https://trello.com/c/4DWSBcYO/201-character-specific-journal

**Comment by Brahman38** [comment]
hahah damn, you're a ninja my friend!!   I'll be keeping an eye out for
this 😎

**Comment by akrigline** [comment]
I'm coming to terms with the fact that this isn't likely to ever happen from me.
