### ISSUE TITLE
Skill Scrolling broken on Firefox

### ISSUE THREAD

**Issue by pikasalt** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#40]
Scrolling behavior on the left hand side of the character sheet is broken on the Firefox browser. The user cannot scroll using a scroll wheel and the visual scroll bar is not present. Tested by myself and a friend. Behavior works as expected while using a chromium-based browser.

**Comment by akrigline** [comment]
Ooof. Thanks for the report. I'll take a look, why does Firefox insist on making life difficult?

**Comment by akrigline** [comment]
resolved in 0.11.3
