### ISSUE TITLE
Add the weight bar

### ISSUE THREAD

**Issue by adacosta92** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#42]
![image](https://user-images.githubusercontent.com/67127175/105854316-c17ed980-5fb4-11eb-8856-611a423be903.png)
Add a bar to show weight carried (especially with variant encumbrance), just like in the default character sheet (on the right, at the bottom of the sheet)

D&D Beyond automatically handles encumbrance, unlike Foundry.

**Comment by akrigline** [comment]
Variant encumbrance is fair. But normal encumbrance should already be supported with the simple weight number above the inventory list.

I suppose it wouldn't hurt to make the bar an optional thing, I personally do not like how much space it eats for something which is so small a part of many games.

**Comment by akrigline** [comment]
I'm probably never going to get around to this, sorry.
