### ISSUE TITLE
Actions Tab not compatible with BetterRolls5e anymore

### ISSUE THREAD

**Issue by adacosta92** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#44]
since the update to using "character actions list dnd5e", clicking the icon only uses core rolls or BOTH core & betterrolls.

**Comment by akrigline** [comment]
What version of better rolls are you using? I believe this was fixed in a better rolls update recently.

**Comment by akrigline** [comment]
dnd5e v1.2.4
Better Rolls 5e v1.3.7
Compact DnDBeyond 5e Character Sheet 0.13.1
Character Actions List dnd5e 1.0.0

I am seeing no duplicate rolls, and all Actions Tab rolls are working with Better Rolls.

**Comment by adacosta92** [comment]
lemme give it another whirl and try to isolate the problem

**Comment by adacosta92** [comment]
couldn't replicate it. works fine now ¯\_(ツ)_/¯
sorry for the hassle :(
