### ISSUE TITLE
Black Screen while Module is Installed

### ISSUE THREAD

**Issue by drcrowswildride** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#46]
#Me and my friend were having issues getting her into the game. We weren't sure why and she tried a bunch of different things to try and get it to work. She tried different browsers, different settings, no ad blocker, enabled Hardware Acceleration and a bunch of other things trying to get it to work. The only two things that worked were when she used a private window but when she reloaded or re-clicked the private window option it wouldn't load again and uninstalling the Beyond 5e sheet and the actions list module. We have no idea why it was doing this but I just wanted to let you know in case others have also had this issue.

**Comment by akrigline** [comment]
That's different...

What version of Foundry Core, dnd5e, and the modules did you have installed?

**Comment by drcrowswildride** [comment]
I had the last most recent update for foundry and the latest update for both 5e and the modules

**Comment by akrigline** [comment]
> I had the last most recent update for foundry and the latest update for both 5e and the modules
> […](#)
> On Feb 18, 2021, at 7:17 PM, Andrew Krigline ***@***.***> wrote: ﻿ That's different... What version of Foundry Core, dnd5e, and the modules did you have installed? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

By most recent update, do you mean 0.8.0 or 0.7.9?

**Comment by drcrowswildride** [comment]
0.7.9

**Comment by akrigline** [comment]
I'll be honest I'm completely blanking on why this might have happened to you. If you're still reproducing this, try uninstalling and reinstalling?
