### ISSUE TITLE
You don't seem to have the module "Character action list dnd5e" active

### ISSUE THREAD

**Issue by DavidJott** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#48]
This message is shown both in the compact and the ogl character sheet. All three modules are enabled (reenabling or reinstalling didn't help). Same when all other modules are disabled.

![#01](https://user-images.githubusercontent.com/80711300/111885928-eac35100-89ca-11eb-8e45-457c1246aea2.jpg)
![#02](https://user-images.githubusercontent.com/80711300/111885930-edbe4180-89ca-11eb-9f17-7e91d4d79b0a.jpg)

[Console Log.txt](https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/files/6176439/Console.Log.txt)

**Comment by akrigline** [comment]
Thanks for the report. There's an issue with actions list 3.0.0 which I should be able to push a fix for today.

**Comment by akrigline** [comment]
Resolved with Actions List 3.0.1, please update if this is happening to you, if it persists, direct any reports to Actions List module's repo. Thanks!
