### ISSUE TITLE
Double "Action" Bars and sheet not work properly

### ISSUE THREAD

**Issue by aomrpg** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#50]
Having an issue where the character sheet is displaying two "Actions" tabs and I cannot access any entry within that tab. If you click on any entry within the "Actions" tab, it will begin to expand the entry but does not cast or trigger the ability. This issue is reproducible/consistent even when it is the only module (and the dependency) activated. Attached is a screenshot of the issue. 
![Compact D D Beyond-like double action tabs](https://user-images.githubusercontent.com/82131646/113968438-15057300-9801-11eb-8848-2dfe09b233b4.PNG)

Foundry version: 0.7.9

Discord tag: Zaryk#8301

**Comment by akrigline** [comment]
Hey, what's the version of the Actions List Module you're using? This was an issue with 3.0.1 that I thought I fixed with 3.0.2

**Comment by aomrpg** [comment]
Thanks for the quick response. I just double checked and the version is 3.03 **BUT** your question prompted a deeper dive into the version of Compact DnD Beyond-like and guess what I found. I host Foundry VTT through the Forge and it appears the Bazaar is updating to version 0.13 instead of 0.15. I manually installed from the manifest URL as a custom module and that did the trick. Here's what it looks like on my end on the Forge. I'm going to let Kakaroto know. To be clear, it works correctly now using version 0.15 and 3.03 of Actions list. 
![image](https://user-images.githubusercontent.com/82131646/114049387-68a3ab00-9859-11eb-9b1f-0b3b95090e22.png)

**Comment by akrigline** [comment]
Ooo good find, I wonder if that was me at some point...

**Comment by aomrpg** [comment]
It looks like they're looking into it, but that's all I know. I put it on the official Forge discord. 
![image](https://user-images.githubusercontent.com/82131646/114051339-ff249c00-985a-11eb-9e75-dce467387180.png)

**Comment by aomrpg** [comment]
Ok update. It looks like the issue was entirely on my end. The Forge has a "Game Manager" that sets the default version of Foundry independent of the game version and it was set to 0.7.7. Once I changed that, everything looks good. Apologies for the false alarm!

**Comment by akrigline** [comment]
thanks for circling back @aomrpg
