### ISSUE TITLE
Set hp.temp to data-dtype Number to fix string concatenation bug

### ISSUE THREAD

**Issue by CeaneC** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#52]
https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/blob/4d7957cd8368f52365d8679d788ff6acbdf04901/src/templates/parts/sheet-header.hbs#L111

Temp HP isn't typed at the moment, so the value is stored as a string when using this character sheet. This leads to problems when using modules like Health Estimate, which (depending on settings) try to add Temp HP and Base HP together.

E.g. a character with 1 temp HP and 16/32 HP would show as having 116/32 HP.

![image](https://user-images.githubusercontent.com/43473593/120177848-fdb69500-c247-11eb-8dba-6899b7cc2ec1.png)

This happens on Foundry 0.7.10, using version 0.15.0 of Compact D&D Beyond Sheet.

**Comment by akrigline** [comment]
Nice catch! Are you willing to open a pull request with this fix for me?
