### ISSUE TITLE
Support for "prepared spells

### ISSUE THREAD

**Issue by paul-tergeist** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#59]

**Comment by paul-tergeist** [comment]
could you add a class="spell-dc" to the first div in <div class="spellcasting-ability"> in the file "actor-spellbooks.hbs" to have the prepared spells show up?

**Comment by akrigline** [comment]
Could I get some details in the description about what exactly this issue is about? I'm super lost

**Comment by paul-tergeist** [comment]
Oh, I just noticed that my title for this ticket is incomplete. It should read: "Support for 'prepared spells' from 'Mess - Moerills enhancing super-suit(e)'". 
That module has the option to give fields for the number of prepared spells in the spellbook tab. As far as I understand the code it looks for a div with the class of .spell-dc and attaches new form fields to that. But this character sheet does not have this class.
Or maybe you could implement such fields yourself? (Moerills are just plain fields, without any calculation)
