### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by kashiichan** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#61]
Hello hello. Minor issue: on the example character sheet, the text in the "damage" section wraps onto a new line. On my character sheet, it doesn't (see Dagger and Shortbow). This means that a lot of the information ends up not visible on the sheet. Have attached a screenshot for your reference. Do you have any suggestions for troubleshooting this? 
![damagesection](https://user-images.githubusercontent.com/100343002/168424926-c992e56f-3654-4451-9019-cbd44244f9ef.jpg)

**Comment by akrigline** [comment]
This has been a thorn in my side for a while, but I finally got around to fixing it at its source:

https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions/releases/tag/v5.0.0

If you update the character actions module, it should be much better overall for this.
