### ISSUE TITLE
Alpha Release as "Latest" Makes PC Sheet "unopenable"

### ISSUE THREAD

**Issue by scott-joe** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#74]
So, the Alpha release looks like it came out a few days ago and it looks like it's tagged as 'latest' so if you update it in VTT, you can no longer open a PC's sheet. I tried pointing the install path to https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/releases/0.21.1/download/module.json or https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/releases/v0.21.1/download/module.json but no dice (🥁)

**Comment by scott-joe** [comment]
I'd never had to do this before, but it looks like you can go and find the module.json in the releases page https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/releases/download/v0.21.1/module.json

**Comment by akrigline** [comment]
Gah, it was meant to be a 'pre-release' so it wouldn't appear as latest. I think I've fixed that, sorry.

I don't suppose you saw any error messages or the like when it was causing your sheet to fail to open? Also what foundry core/dnd5e system version were you on?

**Comment by akrigline** [comment]
(I think i see the issue that caused it to be unopenable, fixed with alpha 2)

**Comment by scottw-kr** [comment]
Sweet. Thanks!
