### ISSUE TITLE
Missing labels on skill name

### ISSUE THREAD

**Issue by scott-joe** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#75]
In version v0.21.1 if you open up the PC screen, the skills/attributes are missing labels. If you click on one, it still knows what it is bc it's asking you what kind of roll you want to make, but the label is missing.
![image](https://user-images.githubusercontent.com/2026866/214679186-40391488-c731-4e0b-aefc-d8188af06327.png)

**Comment by akrigline** [comment]
Gonna close this in favor of #71,
thanks for the report and the image though!

**Comment by scottw-kr** [comment]
No problem. Thanks for the update :)
